### ISSUE TITLE
Grafana 8.0.5: An unexpected error happened

### ISSUE THREAD

**Issue by wols** [panodata/panodata-map-panel#109]
My (first) install `grafana-map-plugin-0.15.0`.

I `Add an empty panel` and select from list `Map panel`...
...a black screen error message only:
```
An unexpected error happened
TypeError: this.events is undefined

Xt@http://localhost:3000/public/build/DashboardPage.cb577348e5e011d82919.js:223:4307
k@http://localhost:3000/public/build/vendors~app.cb577348e5e011d82919.js:2:70367
div
div
div
t@http://localhost:3000/public/build/vendors~app.cb577348e5e011d82919.js:2:706837
h@http://localhost:3000/public/build/app.cb577348e5e011d82919.js:5440:31528
div
div
```
...and so on

**Comment by amotl** [comment]
Hi there,

thank you for reporting your observations. We will try to look into this as soon as possible. Currently, we are heading backwards from vacation.

Maybe @jm66 or @andsens also have some spare cycles to look into it in the meanwhile.

Cheers,
Andreas.

On 12 July 2021 17:07:25 CEST, WOLS ***@***.***> wrote:
>My (first) install `grafana-map-plugin-0.15.0`.
>
>I `Add an empty panel` and select from list `Map panel`...
>...a black screen error message only:
>```
>An unexpected error happened
>TypeError: this.events is undefined
>
***@***.***://localhost:3000/public/build/DashboardPage.cb577348e5e011d82919.js:223:4307
***@***.***://localhost:3000/public/build/vendors~app.cb577348e5e011d82919.js:2:70367
>div
>div
>div
***@***.***://localhost:3000/public/build/vendors~app.cb577348e5e011d82919.js:2:706837
***@***.***://localhost:3000/public/build/app.cb577348e5e011d82919.js:5440:31528
>div
>div
>```
>...and so on
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/panodata/grafana-map-panel/issues/109

-- 
Sent from my mind. This might have been typed on a mobile device, so please excuse my brevity.

**Comment by andsens** [comment]
Running grafana v8.0.3 with [the patched plugin version 0.15.1](https://github.com/panodata/grafana-map-panel/issues/103#issuecomment-875399946) I don't experience this error. New empty dashboard, new empty panel, select "map pane" -> works.

Only error I'm getting is
```
react_devtools_backend.js:2560 Accessing KeybindingSrv not implemented for Grafana 8 yet.
Error: [$injector:unpr] Unknown provider: keybindingSrvProvider <- keybindingSrv
https://errors.angularjs.org/1.8.2/$injector/unpr?p0=keybindingSrvProvider%20%3C-%20keybindingSrv
```

but I'm pretty sure that's the error the aforementioned patch ignores, right?

**Comment by amotl** [comment]
Dear @wols,

can you give the ad hoc build version 0.15.1 from the link @andsens shared within the post above a spin and report back about your observations?

Thanks,
Andreas.

On 12 July 2021 17:24:12 CEST, Anders Ingemann ***@***.***> wrote:
>Running grafana v8.0.3 with [the patched plugin version
>0.15.1](https://github.com/panodata/grafana-map-panel/issues/103#issuecomment-875399946)
>I don't experience this error. New empty dashboard, new empty panel,
>select "map pane" -> works.
>
>Only error I'm getting is
>```
>react_devtools_backend.js:2560 Accessing KeybindingSrv not implemented
>for Grafana 8 yet.
>Error: [$injector:unpr] Unknown provider: keybindingSrvProvider <-
>keybindingSrv
>https://errors.angularjs.org/1.8.2/$injector/unpr?p0=keybindingSrvProvider%20%3C-%20keybindingSrv
>```
>
>but I'm pretty sure that's the error the aforementioned patch ignores,
>right?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/panodata/grafana-map-panel/issues/109#issuecomment-878372479

-- 
Sent from my mind. This might have been typed on a mobile device, so please excuse my brevity.

**Comment by wols** [comment]
`Downloaded grafana-map-panel v0.15.1 zip successfully`

Map panel selected an **no errors** :-) top work!

**Comment by amotl** [comment]
Hi @wols,

thank you for reporting that the patched version works for you already. Kudos to @andsens for publishing it!

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi there,

thank you very much for providing the interim release artefact, @andsens. Finally, I have been able to find some time to issue the regular release (0.16.0), see https://github.com/panodata/panodata-map-panel/releases/tag/0.16.0. We will be happy to receive any feedback how this version works.

Please note that the plugin name changed to `panodata-map-panel` in order to support #112.

With kind regards,
Andreas.

**Comment by amotl** [comment]
According to the feedback here and at #111, I believe we can close this ticket. Thank you again for your contributions!
