### ISSUE TITLE
Problems with multiple metrics in popup content when using InfluxDB

### ISSUE THREAD

**Issue by amotl** [panodata/panodata-map-panel#90]
Dear community,

we are happy to see this fork of the original Worldmap Panel is used by some people for their projects out there [1].

While we integrated #77 by @matschaffer into the most recent release 0.15.0 (thanks again!), @oliveres told us at https://github.com/panodata/grafana-map-panel/pull/77#issuecomment-766438583 that they are not amused:
> Hi, how to hide unwanted fields in popup? I have multiple tags in InfluxDB and I don't want to display this. Thx
>
> <img width="357" alt="Snímek obrazovky 2021-01-24 v 22 51 34" src="https://user-images.githubusercontent.com/31700240/105644651-e715c100-5e96-11eb-867e-8116fef7dd2f.png">

@jm66 and @DmitrySidorow also chimed in. While @matschaffer already provided another patch to revert this change on behalf of #89, I would like to see this going forward rather than backwards. Attaching to that, I would like to follow @jm66's suggestion at https://github.com/panodata/grafana-map-panel/pull/77#issuecomment-768574584 to provide an option in the UI to disable the additional fields.

In the meanwhile, I would like to humbly recommend to just downgrade to version 0.14.0 [2,3], like @jm66 did.

With kind regards,
Andreas.

[1] In this spirit, we will also be happy to see some of the outcomes where this panel has been used if that would be possible and your project policies will permit you to share those. @matschaffer and @robouden are apparently using it for [Safecast](https://en.wikipedia.org/wiki/Safecast_(organization)). While we haven't been able to create a documentation page including some sort of gallery/exhibition yet, that would definitively be a nice thing to have.
[2] https://github.com/panodata/grafana-map-panel/releases/tag/0.14.0
[3] https://github.com/panodata/grafana-map-panel/releases/download/0.14.0/grafana-map-panel-0.14.0.zip

**Comment by DmitrySidorow** [comment]
I use this to track the quality of data transmission from passenger carriages
![Screenshot_1](https://user-images.githubusercontent.com/43705385/106292935-7b4ca300-625e-11eb-9544-d80912148455.png)
![Screenshot_2](https://user-images.githubusercontent.com/43705385/106292941-7be53980-625e-11eb-94b4-d5d1b3d539ec.png)

In the future, carriages with errors and accidents will also be shown on the another map.

Customizable popup would be killer feauture :smiley:

**Comment by jm66** [comment]
Hi @amotl, first of all, thanks for all that you do to maintain this plugin. The feature integrated in  #77 by @matschaffer looks like a great addition and would be even better if we can decide from the UI wether to show "label", "all" or select which fields should be shown.

We are using this great plugin to show the number of active wireless users connected to the campus wireless network. https://wifimap.eis.utoronto.ca/

Again, thanks a lot.
JM

**Comment by matschaffer** [comment]
My thinking on my first pass was to use the query metrics to show/hide entries in the popup.

This way we can use the query panel as UI to select which fields. If you don't want it, leave it out of the query, if you want it, include it.

![LiZZ1wZZOm](https://user-images.githubusercontent.com/690/106347290-bb646200-6300-11eb-9480-1f3c33b35ebc.gif)

I'm thinking what we can do is work out what other "special" fields (when, timestamp, etc) show up in other data sources and filter those as well in this code: https://github.com/panodata/grafana-map-panel/pull/77/files#diff-eac8713e7ec990341c87c6c0d1787ac626e2055b7e6f9d62c524771aa35c0a74R442

Alternatively, we could do a comma-separated list of fields to include, but I liked the simplicity of using the query panel to control field retrieval & visibility.

**Comment by oliveres** [comment]
Hi @matschaffer, this is not a universal solution because in InfluxDB v2 you cannot select some and unselect other fields. Flux query language working with filtering only, there is no SELECT xy FROM yz WHERE...(at least what I know about it). Comma-separated field names in UI settings will be OK.

**Comment by amotl** [comment]
Hi everyone,

I just created #118, where I tried to summarize the topic about customizing the popup contents as good as possible, taking requests from different users into account.

With kind regards,
Andreas.

**Comment by matschaffer** [comment]
With https://github.com/panodata/panodata-map-panel/pull/89 merged I think we can close this in favor of https://github.com/panodata/panodata-map-panel/issues/118
